### ISSUE TITLE
Linode-cli 2.8.0 fails

### ISSUE THREAD

**Issue by GimpMaster** [linode/linode-cli#134]
dev@localhost:~$ linode-cli linodes list --all
Traceback (most recent call last):
  File "/usr/local/bin/linode-cli", line 11, in <module>
    sys.exit(main())
  File "/home/dev/.local/lib/python2.7/site-packages/linodecli/__init__.py", line 424, in main
    cli.handle_command(parsed.command, parsed.action, args)
  File "/home/dev/.local/lib/python2.7/site-packages/linodecli/cli.py", line 444, in handle_command
    result = self.do_request(operation, args)
  File "/home/dev/.local/lib/python2.7/site-packages/linodecli/cli.py", line 377, in do_request
    result =  method(url, headers=headers, data=body)
  File "/home/dev/.local/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/dev/.local/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dev/.local/lib/python2.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/home/dev/.local/lib/python2.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/dev/.local/lib/python2.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/home/dev/.local/lib/python2.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/linode/instances?page=1': No schema supplied. Perhaps you meant http:///linode/instances?page=1?

Reverting back to 2.7.1 fixes this issue. Any thoughts?

**Comment by amar-myana** [comment]
Same here

**Comment by Dorthu** [comment]
Thanks for reporting; I'm looking into this now

**Comment by Dorthu** [comment]
Looks like this only impacts python 2; installing 2.8.0 on python3 works as expected.  I'm going to do some debugging and release a fixed 2.8.1 that works in python2 and python3 shortly

**Comment by Dorthu** [comment]
`linode-cli 2.8.1` is on pypi and should resolve this issue.  You can update it with a `pip install --upgrade linode-cli`.  

Sorry for the inconvenience, please let me know if you have any other issues!

**Comment by GimpMaster** [comment]
Thanks. I’ll give it a try!

**Comment by amar-myana** [comment]
Thanks @GimpMaster. The issue has been resolved.
