### ISSUE TITLE
Passing the token in the LINODE_CLI_TOKEN environment variable, without doing an init first needs --no-defaults

### ISSUE THREAD

**Issue by atleta** [linode/linode-cli#140]
Hi,

The documentation (README.md) claims that if I set the token in the LINODE_CLI_TOKEN then I can just use linode-cli without doing a `linode-cli init` first (which, I guess, unavoidably uses the console for input). However, this only works if I pass the --no-defaults parameter and this is undocumented (doesn't follow from the documentation). It seems not to be needed with some commands (e.g. `nodebalancers list` does work), while needed with others (I had a problem with `nodebalancers config-update). This is the exception I get:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 786, in get
    value = d[option]
  File "/usr/local/lib/linode-cli/env/lib/python3.5/collections/__init__.py", line 881, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/lib/linode-cli/env/lib/python3.5/collections/__init__.py", line 873, in __missing__
    raise KeyError(key)
KeyError: 'default-user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/linode-cli/env/bin/linode-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/linode-cli/env/lib/python3.5/site-packages/linodecli/__init__.py", line 424, in main
    cli.handle_command(parsed.command, parsed.action, args)
  File "/usr/local/lib/linode-cli/env/lib/python3.5/site-packages/linodecli/cli.py", line 481, in handle_command
    result = self.do_request(operation, args)
  File "/usr/local/lib/linode-cli/env/lib/python3.5/site-packages/linodecli/cli.py", line 361, in do_request
    parsed_args = self.config.update(parsed_args)
  File "/usr/local/lib/linode-cli/env/lib/python3.5/site-packages/linodecli/configuration.py", line 86, in update
    username = self.username or self.default_username()
  File "/usr/local/lib/linode-cli/env/lib/python3.5/site-packages/linodecli/configuration.py", line 63, in default_username
    return self.config.get('DEFAULT', 'default-user')
  File "/usr/lib/python3.5/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'default-user' in section: 'DEFAULT'
```

I'm running the following version:
```
linode-cli 2.10.1
Built off spec version 4.6.0
```

I guess this is just a documentation bug, but included the traceback just in case it's unintended behavior.

**Comment by Dorthu** [comment]
Thanks for reporting this, sorry it took me a while to find it!  I can reproduce this issue locally, and I suspect I know the cause - should have a fix up soon.
