### ISSUE TITLE
Retrieving disk usage crashes

### ISSUE THREAD

**Issue by dkam** [linode/linode-cli#159]
Determining object storage usage crashes the client:

```bash
$ linode-cli obj du
Traceback (most recent call last):
  File "/usr/local/bin/linode-cli", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/linodecli/__init__.py", line 367, in main
    plugins.invoke(parsed.command, plugin_args, context)
  File "/usr/local/lib/python2.7/site-packages/linodecli/plugins/__init__.py", line 33, in invoke
    plugin.call(args, context)
  File "/usr/local/lib/python2.7/site-packages/linodecli/plugins/obj.py", line 566, in call
    COMMAND_MAP[parsed.command](client, args)
  File "/usr/local/lib/python2.7/site-packages/linodecli/plugins/obj.py", line 435, in show_usage
    tab = _borderless_table([[_pad_to(total, length=7), '{} objects'.format(num), b.name]])
  File "/usr/local/lib/python2.7/site-packages/linodecli/plugins/obj.py", line 732, in _pad_to
    ret = ret + padding
UnboundLocalError: local variable 'padding' referenced before assignment
```

**Comment by dkam** [comment]
Further info: 

```shell
 $ pip install linode-cli --upgrade
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: linode-cli in /usr/local/lib/python2.7/site-packages (2.10.3)
Requirement already satisfied, skipping upgrade: terminaltables in /usr/local/lib/python2.7/site-packages (from linode-cli) (3.1.0)
Requirement already satisfied, skipping upgrade: requests in /usr/local/lib/python2.7/site-packages (from linode-cli) (2.22.0)
Requirement already satisfied, skipping upgrade: PyYAML in /usr/local/lib/python2.7/site-packages (from linode-cli) (5.1.2)
Requirement already satisfied, skipping upgrade: colorclass in /usr/local/lib/python2.7/site-packages (from linode-cli) (2.2.0)
Requirement already satisfied, skipping upgrade: enum34 in /usr/local/lib/python2.7/site-packages (from linode-cli) (1.1.6)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests->linode-cli) (1.25.7)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests->linode-cli) (2019.9.11)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests->linode-cli) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/local/lib/python2.7/site-packages (from requests->linode-cli) (2.8)
```

**Comment by Dorthu** [comment]
There was a recent change to this code, it must be related.  Looking now
