### ISSUE TITLE
LKE cluster creation via CLI not matching curl

### ISSUE THREAD

**Issue by kodumbeats** [linode/linode-cli#166]
The APIv4 documentation lists the following requirements for https://api.linode.com/v4beta/lke/clusters:
- label, region, version, and node pools (array)

The curl example correctly posts the json for the endpoint, but the CLI tool doesn't match the behavior.
```
$ linode-cli lke cluster-create --region us-central --label test --version 1.16 --node_pools [ {"type": "g6-standard-4"}, {"count": 3} ]
usage: linode-cli [-h] [--node_pools.type type] [--tags tags]
                  [--region region] [--label label] [--version version]
                  [--node_pools.count count]
linode-cli: error: ambiguous option: --node_pools could match --node_pools.type, --node_pools.count
```
However, using `node_pools.type` and `node_pools.count` results in a json parsing error:
```
$ linode-cli lke cluster-create --region us-central --label test --version 1.16 --node_pools.type g6-standard-4 --node_pools.count 3
Traceback (most recent call last):
  File "/usr/local/bin/linode-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/linodecli/__init__.py", line 430, in main
    cli.handle_command(parsed.command, parsed.action, args)
  File "/usr/local/lib/python2.7/site-packages/linodecli/cli.py", line 512, in handle_command
    result = self.do_request(operation, args)
  File "/usr/local/lib/python2.7/site-packages/linodecli/cli.py", line 404, in do_request
    cur[k.split('.')[-1]] = v
TypeError: list indices must be integers, not str
```
```
$ linode-cli --version
linode-cli 2.11.0
Built off spec version 4.10.0
```

**Comment by Dorthu** [comment]
Thanks for the report, I'm looking into this now

**Comment by Dorthu** [comment]
#167 fixes this issue.  I'll have it reviewed and shipped later today.  Sorry for the inconvenience!
