### ISSUE TITLE
linode-cli obj plugin hanging connection

### ISSUE THREAD

**Issue by mathewtrivett** [linode/linode-cli#175]
Thanks for making the linode-cli.

I'm trying to connect to the new object storage service but the command just hangs and then on killing the process I get the below stacktrace.

This is the command I'm running `linode-cli obj ls`.

## System

Python: 3.6
Boto: 2.49.0
linode-cli: 2.13.1
Built off spec version 4.14.0
Mac OSX: 10.14.6

## Stacktrace

```
File "/Library/Frameworks/Python.framework/Versions/3.6/bin/linode-cli", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linodecli/__init__.py", line 373, in main
    plugins.invoke(parsed.command, plugin_args, context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linodecli/plugins/__init__.py", line 33, in invoke
    plugin.call(args, context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linodecli/plugins/obj.py", line 578, in call
    COMMAND_MAP[parsed.command](client, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linodecli/plugins/obj.py", line 80, in list_objects_or_buckets
    buckets = client.get_all_buckets()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/boto/s3/connection.py", line 443, in get_all_buckets
    response = self.make_request('GET', headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/boto/s3/connection.py", line 671, in make_request
    retry_handler=retry_handler
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/boto/connection.py", line 1019, in _mexe
    time.sleep(next_sleep)
```

It looks like it is struggling to make a connection? My access token works fine as I can access all other resources. Not sure if I'm doing something wrong here?

Looking forward to testing the new object storage service

**Comment by Dorthu** [comment]
From your machine, can you `curl -v https://us-east-1.linodeobjects.com`?  Also, does the same issue occur if you run `linode-cli obj ls --cluster eu-central-1`?

**Comment by mathewtrivett** [comment]
Here is the output from curl:

```
* Rebuilt URL to: https://us-east-1.linodeobjects.com/
*   Trying 45.79.157.59...
* TCP_NODELAY set
* Connected to us-east-1.linodeobjects.com (45.79.157.59) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=linodeobjects.com
*  start date: Feb 10 16:10:24 2020 GMT
*  expire date: May 10 16:10:24 2020 GMT
*  subjectAltName: host "us-east-1.linodeobjects.com" matched cert's "us-east-1.linodeobjects.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: us-east-1.linodeobjects.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 24 Mar 2020 17:28:58 GMT
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Connection: keep-alive
< x-amz-request-id: tx0000000000000017bada1-005e7a435a-e9b09e-default
< 
* Connection #0 to host us-east-1.linodeobjects.com left intact
<?xml version="1.0" encoding="UTF-8"?><ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>anonymous</ID><DisplayName></DisplayName></Owner><Buckets></Buckets></ListAllMyBucketsResult>
```

But when running `linode-cli obj ls --cluster eu-central-1` I get a hung connection again and the same error:

```
^CTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/linode-cli", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linodecli/__init__.py", line 373, in main
    plugins.invoke(parsed.command, plugin_args, context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linodecli/plugins/__init__.py", line 33, in invoke
    plugin.call(args, context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linodecli/plugins/obj.py", line 578, in call
    COMMAND_MAP[parsed.command](client, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linodecli/plugins/obj.py", line 80, in list_objects_or_buckets
    buckets = client.get_all_buckets()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/boto/s3/connection.py", line 443, in get_all_buckets
    response = self.make_request('GET', headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/boto/s3/connection.py", line 671, in make_request
    retry_handler=retry_handler
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/boto/connection.py", line 1019, in _mexe
    time.sleep(next_sleep)
KeyboardInterrupt
```

I tried using the same credentials with the s3cmd tool also and whilst I could delete a bucket I wasn't then able to create a bucket or really anything else? I'm not sure if it is a credentials thing? But it is weird I could manually create a bucket on linode.com but then delete it from s3cmd? 🤷‍♂️

**Comment by Dorthu** [comment]
That is very strange 🤔 If s3cmd is behaving (mostly) the same way, I'll forwarded this to our object storage team and see what they think.  I'll keep you updated.

**Comment by mathewtrivett** [comment]
Thanks, appreciate the rapid response and helping to dig into the issue

**Comment by Dorthu** [comment]
Our object storage team requested that you open a Support Ticket so they can continue looking into this issue with you.  You can open a ticket at this link: https://cloud.linode.com/support/tickets. Sorry for the inconvenience.

**Comment by mathewtrivett** [comment]
Ok thanks for looking into it for me. I'll raise a ticket. I'll close this ticket but link back to it on the support ticket
