### ISSUE TITLE
How to install from github?

### ISSUE THREAD

**Issue by tamalsaha** [linode/linode-cli#241]
I am trying to install this cli from github due to #239 . But I am getting the following error:

```
$ python3 -m pip install git+https://github.com/linode/linode-cli@master#egg=linode-cli

WARNING: Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/lib/python3.6/dist-packages
sysconfig: /usr/lib/python3.6/site-packages
WARNING: Value for scheme.purelib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/lib/python3.6/dist-packages
sysconfig: /usr/lib/python3.6/site-packages
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/include/python3.6/UNKNOWN
sysconfig: /usr/include/python3.6m
WARNING: Value for scheme.scripts does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/bin
sysconfig: /usr/bin
WARNING: Value for scheme.data does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local
sysconfig: /usr
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Defaulting to user installation because normal site-packages is not writeable
Collecting linode-cli
  Cloning https://github.com/linode/linode-cli (to revision master) to /tmp/pip-install-vima1vwy/linode-cli_8d910f5976dc4095bdd6d41df2be4c4b
  Running command git clone -q https://github.com/linode/linode-cli /tmp/pip-install-vima1vwy/linode-cli_8d910f5976dc4095bdd6d41df2be4c4b
  Running command git submodule update --init --recursive -q
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from linode-cli) (3.12)
Requirement already satisfied: colorclass in /home/tamal/.local/lib/python3.6/site-packages (from linode-cli) (2.2.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from linode-cli) (2.18.4)
Requirement already satisfied: terminaltables in /home/tamal/.local/lib/python3.6/site-packages (from linode-cli) (3.1.0)
Building wheels for collected packages: linode-cli
  Building wheel for linode-cli (setup.py) ... done
  Created wheel for linode-cli: filename=linode_cli-5.1.0-py3-none-any.whl size=45633 sha256=441a6aebb44fe8d73b5781a1876f0da499c4f255e4727a0a012a3efb56f4a0c0
  Stored in directory: /tmp/pip-ephem-wheel-cache-uev15tf3/wheels/8b/53/08/531cb554351b45cb1e44580f4a24745c9fb844abd18a39cc7c
Successfully built linode-cli
Installing collected packages: linode-cli
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
  distutils: /home/tamal/.local/include/python3.6m/linode-cli
  sysconfig: /home/tamal/.local/include/python3.6/linode-cli
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /home/tamal/.local/include/python3.6m/UNKNOWN
sysconfig: /home/tamal/.local/include/python3.6
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
Successfully installed linode-cli-5.1.0

$ linode-cli volumes list --json --pretty
No spec baked.  Please bake by calling this script as follows:
  python3 gen_cli.py bake /path/to/spec

```

How do I solve this? Thanks.

**Comment by Dorthu** [comment]
The CLI is generated from Linode's OpenAPI specification; the code hosted here is missing the crucial data that gives it operations, which is why you're receiving that error.

The recommend way to get the CLI is off of PyPI, with a `pip install linode-cli`.  These builds wil have passed our internal test suite and be verified as "working," and will include the latest data baked in.

If you prefer to build from source, instructions are in [the README](https://github.com/linode/linode-cli#installation) (although in the aboe, ` make install` is probably what you're mising).

**Comment by tamalsaha** [comment]
I installed using pip. But I am still getting the same error. So, I thought I need to build from source.

```
+ linode-cli volumes delete 139892
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tamal/.local/bin/linode-cli", line 8, in <module>
    sys.exit(main())
  File "/home/tamal/.local/lib/python3.6/site-packages/linodecli/__init__.py", line 461, in main
    cli.handle_command(parsed.command, parsed.action, args)
  File "/home/tamal/.local/lib/python3.6/site-packages/linodecli/cli.py", line 560, in handle_command
    result = self.do_request(operation, args)
  File "/home/tamal/.local/lib/python3.6/site-packages/linodecli/cli.py", line 434, in do_request
    parsed_args = self.config.update(parsed_args)
  File "/home/tamal/.local/lib/python3.6/site-packages/linodecli/configuration.py", line 136, in update
    return self.update_namespace(namespace, dict(self.config.items(username)))
  File "/usr/lib/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: ''
+ true
+ sleep 1
^C⏎                                                                                                  
$ linode-cli --version
linode-cli 5.0.1
Built off spec version 4.86.1

```

**Comment by tamalsaha** [comment]
It is working after I installed the latest version. pip was using locally cached version,
