### ISSUE TITLE
SSLCert error when listing obj

### ISSUE THREAD

**Issue by klreeher** [linode/linode-cli#291]
I was following the [linode guide to using the linode-cli](https://www.linode.com/docs/guides/linode-cli/) and I ran into an issue working with my object storage. 

I configured my CLI with a PAT, and I can list my linode volumes, etc, but when I attempt to list my object storage buckets, I get an SSL error. 

os info:
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000

python info: Python 3.9.4

I'm getting this error when I run the linode-cli from both powershell and windows cmd prompt.

```
PS C:\Users\kreeh> linode-cli obj ls
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\linode-cli.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\linodecli\__init__.py", line 509, in main
    plugins.invoke(parsed.command, plugin_args, context)
  File "c:\python39\lib\site-packages\linodecli\plugins\__init__.py", line 34, in invoke
    plugin.call(args, context)
  File "c:\python39\lib\site-packages\linodecli\plugins\obj.py", line 830, in call
    COMMAND_MAP[parsed.command](get_client, args)
  File "c:\python39\lib\site-packages\linodecli\plugins\obj.py", line 123, in list_objects_or_buckets
    buckets = client.get_all_buckets()
  File "c:\python39\lib\site-packages\boto\s3\connection.py", line 443, in get_all_buckets
    response = self.make_request('GET', headers=headers)
  File "c:\python39\lib\site-packages\boto\s3\connection.py", line 667, in make_request
    return super(S3Connection, self).make_request(
  File "c:\python39\lib\site-packages\boto\connection.py", line 1070, in make_request
    return self._mexe(http_request, sender, override_num_retries,
  File "c:\python39\lib\site-packages\boto\connection.py", line 1030, in _mexe
    raise ex
  File "c:\python39\lib\site-packages\boto\connection.py", line 942, in _mexe
    connection.request(request.method, request.path,
  File "c:\python39\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\python39\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\python39\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\python39\lib\http\client.py", line 1008, in _send_output
    self.send(msg)
  File "c:\python39\lib\http\client.py", line 948, in send
    self.connect()
  File "c:\python39\lib\http\client.py", line 1422, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "c:\python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "c:\python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "c:\python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)
PS C:\Users\kreeh>
```

**Comment by Dorthu** [comment]
I can't reproduce this on my end.  Which object storage cluster were you attempting to list buckets in?

**Comment by klreeher** [comment]
I was prompted initially to set a default, and I set `us-southeast-1`, which is where my bucket is. However, even if I override this with a different cluster, I get the same error.

```
PS C:\Users\kreeh> linode-cli obj ls --cluster eu-central-1
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\linode-cli.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\linodecli\__init__.py", line 509, in main
    plugins.invoke(parsed.command, plugin_args, context)
  File "c:\python39\lib\site-packages\linodecli\plugins\__init__.py", line 34, in invoke
    plugin.call(args, context)
  File "c:\python39\lib\site-packages\linodecli\plugins\obj.py", line 830, in call
    COMMAND_MAP[parsed.command](get_client, args)
  File "c:\python39\lib\site-packages\linodecli\plugins\obj.py", line 123, in list_objects_or_buckets
    buckets = client.get_all_buckets()
  File "c:\python39\lib\site-packages\boto\s3\connection.py", line 443, in get_all_buckets
    response = self.make_request('GET', headers=headers)
  File "c:\python39\lib\site-packages\boto\s3\connection.py", line 667, in make_request
    return super(S3Connection, self).make_request(
  File "c:\python39\lib\site-packages\boto\connection.py", line 1070, in make_request
    return self._mexe(http_request, sender, override_num_retries,
  File "c:\python39\lib\site-packages\boto\connection.py", line 1019, in _mexe
    time.sleep(next_sleep)
KeyboardInterrupt
PS C:\Users\kreeh> linode-cli obj --cluster eu-central-1 ls
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\linode-cli.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\linodecli\__init__.py", line 509, in main
    plugins.invoke(parsed.command, plugin_args, context)
  File "c:\python39\lib\site-packages\linodecli\plugins\__init__.py", line 34, in invoke
    plugin.call(args, context)
  File "c:\python39\lib\site-packages\linodecli\plugins\obj.py", line 830, in call
    COMMAND_MAP[parsed.command](get_client, args)
  File "c:\python39\lib\site-packages\linodecli\plugins\obj.py", line 123, in list_objects_or_buckets
    buckets = client.get_all_buckets()
  File "c:\python39\lib\site-packages\boto\s3\connection.py", line 443, in get_all_buckets
    response = self.make_request('GET', headers=headers)
  File "c:\python39\lib\site-packages\boto\s3\connection.py", line 667, in make_request
    return super(S3Connection, self).make_request(
  File "c:\python39\lib\site-packages\boto\connection.py", line 1070, in make_request
    return self._mexe(http_request, sender, override_num_retries,
  File "c:\python39\lib\site-packages\boto\connection.py", line 1030, in _mexe
    raise ex
  File "c:\python39\lib\site-packages\boto\connection.py", line 942, in _mexe
    connection.request(request.method, request.path,
  File "c:\python39\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\python39\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\python39\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\python39\lib\http\client.py", line 1008, in _send_output
    self.send(msg)
  File "c:\python39\lib\http\client.py", line 948, in send
    self.connect()
  File "c:\python39\lib\http\client.py", line 1422, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "c:\python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "c:\python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "c:\python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)
PS C:\Users\kreeh>
```

**Comment by klreeher** [comment]
I don't know if it's helpful, but I don't get this error when I use boto directly via a python script to list the objects.

**Comment by Dorthu** [comment]
We've retested this internally, this time on Windows, and still can't reproduce the error you're seeing.

The certificates for the us-southeast-1 cluster are valid through March 30th: 

```
wsmith@linode$ curl https://us-southeast-1.linodeobjects.com -vvv 2>&1 | grep expire
*  expire date: Mar 30 19:37:10 2022 GMT
```

Any chance your system time is set forward past that date?  What was the code you used to test this with boto without the CLI?
