### ISSUE TITLE
Unable to parse API response when doing linode-cli databases types

### ISSUE THREAD

**Issue by gferon** [linode/linode-cli#297]
With the latest `linode-cli` available on PyPI, I get the following stacktrace when running `linode-cli databases types`.

```
Traceback (most recent call last):
  File "/home/gferon/.local/bin/linode-cli", line 8, in <module>
    sys.exit(main())
  File "/home/gferon/.local/lib/python3.10/site-packages/linodecli/__init__.py", line 573, in main
    cli.handle_command(parsed.command, parsed.action, args)
  File "/home/gferon/.local/lib/python3.10/site-packages/linodecli/cli.py", line 683, in handle_command
    operation.process_response_json(result.json(), self.output_handler)
  File "/home/gferon/.local/lib/python3.10/site-packages/linodecli/operation.py", line 311, in process_response_json
    json = self.response_model.fix_json(json)
  File "/home/gferon/.local/lib/python3.10/site-packages/linodecli/response.py", line 174, in fix_json
    for item in nlist:
TypeError: 'NoneType' object is not iterable
```

it seems that `self.nlist` is `None` and I'm not exactly sure, but it could be related to `x-linode-cli-nested-list: cluster_type` in https://www.linode.com/docs/api/openapi.yaml?

**Comment by Dorthu** [comment]
This is indeed because of the nested list, but it looks like the issue goes deeper, and will require a CLI code change as well.  I'm looking into it.  Thanks for the report 👍

**Comment by Dorthu** [comment]
The two PRs linked above combine to resolve this issue.  Thank you again for reporting it 🙇
