### ISSUE TITLE
[Bug]: Error configuring the cli

### ISSUE THREAD

**Issue by gathecageorge** [linode/linode-cli#356]
### CLI Version

linode-cli 5.30.0 Built off spec version 4.143.2

### Command

linode-cli configure --token

It says "Configuring myusername...." then stays like that forever. When I cancel it, I get error below.

Sometimes it doesnt even show the message "Configuring myusername..."

### Output

^CTraceback (most recent call last):
  File "/home/username/.local/bin/linode-cli", line 5, in <module>
    from linodecli import main
  File "/home/username/.local/lib/python3.10/site-packages/linodecli/__init__.py", line 36, in <module>
    cli = CLI(VERSION, BASE_URL, skip_config=skip_config)
  File "/home/username/.local/lib/python3.10/site-packages/linodecli/cli.py", line 43, in __init__
    self.config = CLIConfig(self.base_url, skip_config=skip_config)
  File "/home/username/.local/lib/python3.10/site-packages/linodecli/configuration.py", line 94, in __init__
    self.configure()
  File "/home/username/.local/lib/python3.10/site-packages/linodecli/configuration.py", line 530, in configure
    username, config["token"] = self._get_token_terminal()
  File "/home/username/.local/lib/python3.10/site-packages/linodecli/configuration.py", line 351, in _get_token_terminal
    username = self._username_for_token(token)
  File "/home/username/.local/lib/python3.10/site-packages/linodecli/configuration.py", line 327, in _username_for_token
    u = self._do_get_request("/profile", token=token, exit_on_error=False)
  File "/home/username/.local/lib/python3.10/site-packages/linodecli/configuration.py", line 697, in _do_get_request
    return self._do_request(
  File "/home/username/.local/lib/python3.10/site-packages/linodecli/configuration.py", line 722, in _do_request
    result = method(self.base_url + url, headers=headers, json=body)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
KeyboardInterrupt

### Expected Behavior

Should be able to configure the token

### Actual Behavior

Is not responding

### Steps to Reproduce

just do linode-cli configure --token and paste the token.

Running ubuntu 22.04 and python 3.10

**Comment by lgarber-akamai** [comment]
@gathecageorge Thanks for the report!

I've tested this on a Linode running Ubuntu 22.04 and haven't been able to reproduce this issue quite yet. Judging by the trace you posted, it looks like the CLI is hanging when attempting to make a GET request to `/profile`.


Could you try manually creating a config file in `~/.config/linode-cli` with the following contents:

```[DEFAULT]
default-user = myusername

[myusername]
token = mytoken
```

then run `linode-cli linodes ls` to see if the same issue occurs?

**Comment by gathecageorge** [comment]
Think I figured my problem, it occurs only on windows subsystem for linux (Windows 11 and Ubuntu 22.04).

When I create the file above, just missing [DEFAULT] at the start to look like
`
[DEFAULT]
default-user = myusername

[myusername]
token = mytoken
`
then it works okay like 50% of the times, other times it just hangs. Have opted to use the docker version and add alias for now.

**Comment by lgarber-akamai** [comment]
Glad you got it working!
