### ISSUE TITLE
[Bug]: Error creating linodes

### ISSUE THREAD

**Issue by FlorentMasson** [linode/linode-cli#378]
### CLI Version

5.32.0

### Command

`linode-cli linodes create --region us-east --label test --root_pass <redacted> --authorized_keys 'ssh-rsa <redacted> root@server'`

### Output

Traceback (most recent call last):
  File "/usr/local/bin/linode-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/linodecli/__init__.py", line 610, in main
    cli.handle_command(parsed.command, parsed.action, args)
  File "/usr/local/lib/python3.8/dist-packages/linodecli/cli.py", line 476, in handle_command
    result = do_request(self, operation, args)
  File "/usr/local/lib/python3.8/dist-packages/linodecli/api_request.py", line 40, in do_request
    body = _build_request_body(ctx, operation, parsed_args)
  File "/usr/local/lib/python3.8/dist-packages/linodecli/api_request.py", line 108, in _build_request_body
    parsed_args = ctx.config.update(parsed_args, operation.allowed_defaults)
  File "/usr/local/lib/python3.8/dist-packages/linodecli/configuration/__init__.py", line 239, in update
    value = allowed_defaults[key]
TypeError: list indices must be integers or slices, not str

### Expected Behavior

Linode created successfully

### Actual Behavior

Error message

### Steps to Reproduce

After upgrading linode-cli on ubuntu (to 5.32.0), I got this error. My linode creation scripts have not changed 
I had to revert to 5.31.0 and everything went back to working

**Comment by jriddle-linode** [comment]
Thanks for the report it looks like an issue with the config parsing changes we made. Will update with a PR here soon.

**Comment by jriddle-linode** [comment]
Weird i'm not able to recreate it on my end. Can you show your `~/.config/linode-cli` file? When i try running the same command as you I get a provisioning server.

**Comment by FlorentMasson** [comment]
[DEFAULT]
default-user = username

[username]
token = <redacted>
region = us-east
type = g6-dedicated-2
image = linode/ubuntu20.04

**Comment by jriddle-linode** [comment]
@FlorentMasson new version released v5.32.1, please let us know if you have anymore trouble!

**Comment by FlorentMasson** [comment]
Looks good, thanks!
