### ISSUE TITLE
completion command should not require PAT token

### ISSUE THREAD

**Issue by chenrui333** [linode/linode-cli#607]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  Traceback (most recent call last):
    File "/home/linuxbrew/.linuxbrew/Cellar/linode-cli/5.49.0/bin/linode-cli", line 5, in <module>
      from linodecli import main
    File "/home/linuxbrew/.linuxbrew/Cellar/linode-cli/5.49.0/libexec/lib/python3.12/site-packages/linodecli/__init__.py", line 43, in <module>
      cli = CLI(VERSION, handle_url_overrides(BASE_URL), skip_config=skip_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/linuxbrew/.linuxbrew/Cellar/linode-cli/5.49.0/libexec/lib/python3.12/site-packages/linodecli/cli.py", line 39, in __init__
      self.config = CLIConfig(self.base_url, skip_config=skip_config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/linuxbrew/.linuxbrew/Cellar/linode-cli/5.49.0/libexec/lib/python3.12/site-packages/linodecli/configuration/config.py", line 72, in __init__
      self.configure()
    File "/home/linuxbrew/.linuxbrew/Cellar/linode-cli/5.49.0/libexec/lib/python3.12/site-packages/linodecli/configuration/config.py", line 369, in configure
      username, config["token"] = _get_token_terminal(self.base_url)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/linuxbrew/.linuxbrew/Cellar/linode-cli/5.49.0/libexec/lib/python3.12/site-packages/linodecli/configuration/auth.py", line 222, in _get_token_terminal
      token = input("Personal Access Token: ")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  EOFError: EOF when reading a line
  Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /home/linuxbrew/.linuxbrew/Cellar/linode-cli/5.49.0/bin/linode-cli completion bash` exited with 1. Here's the output:
  Welcome to the Linode CLI.  This will walk you through some initial setup.
  
  First, we need a Personal Access Token.  To get one, please visit
  https://cloud.linode.com/profile/tokens and click
  "Create a Personal Access Token".  The CLI needs access to everything
  on your account to work correctly.
  Personal Access Token: 
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/8915715416/job/24485909471?pr=170570
relates to Homebrew/homebrew-core#170570

**Comment by ykim-1** [comment]
Hey @chenrui333, it seems you've already addressed this issue. We'll review it tomorrow and aim to release a patch shortly after

**Comment by chenrui333** [comment]
yeah, totally, thanks! :)
