### ISSUE TITLE
linode list generates AttributeError: 'NoneType' object has no attribute 'storage'

### ISSUE THREAD

**Issue by rmcintosh** [linode/linode-cli#7]
```
linode-cli list
Linode
┌─────────────┬─────────┬────────────┬─────────┬─────────┬──────┐
│ label       │ status  │ location   │ backups │ storage │ ram  │
├─────────────┼─────────┼────────────┼─────────┼─────────┼──────┤
│ salt-master │ running │ Newark, NJ │ yes     │ 20480   │ 1024 │
│ nagios      │ running │ Newark, NJ │ yes     │ 20480   │ 1024 │
│ urmom       │ running │ Newark, NJ │ yes     │ 20480   │ 1024 │
│ cowrie      │ running │ Newark, NJ │ yes     │ 20480   │ 1024 │
└─────────────┴─────────┴────────────┴─────────┴─────────┴──────┘
Work
Traceback (most recent call last):
  File "/usr/local/bin/linode-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/linodecli/cli.py", line 85, in main
    getattr(obj, cmd)(args, client, unparsed=unparsed)
  File "/usr/local/lib/python3.6/site-packages/linodecli/resources/linode.py", line 88, in list
    data = [ _make_linode_row(l) for l in groups[k] ]
  File "/usr/local/lib/python3.6/site-packages/linodecli/resources/linode.py", line 88, in <listcomp>
    data = [ _make_linode_row(l) for l in groups[k] ]
  File "/usr/local/lib/python3.6/site-packages/linodecli/resources/linode.py", line 36, in _make_linode_row
    linode.type.storage,
AttributeError: 'NoneType' object has no attribute 'storage'
```

**Comment by Dorthu** [comment]
I'm guessing you have a Linode in an unusual configuration. I believe this will be resolved in the API in the coming weeks.

**Comment by Dorthu** [comment]
Is this the same issue as #4?
