### ISSUE TITLE
[Bug]: Error when viewing details for an image using either tabular or text output.

### ISSUE THREAD

**Issue by leonardobdes** [linode/linode-cli#707]
### CLI Version

linode-cli v5.55.0 Built from spec version 4.191.1

### Command

linode-cli images view linode/debian12-kube-v1.31.0

### Output

      ┌──────────────────────────────┬────────────────────────────────┬────────┬─────────────┬───────────┬──────┬───────────┬──────────────┬────────────┬──────┐
│ id                           │ label                          │ vendor │ description │ is_public │ size │ status    │ capabilities │ total_size │ tags │
├──────────────────────────────┼────────────────────────────────┼────────┼─────────────┼───────────┼──────┼───────────┼──────────────┼────────────┼──────┤
│ linode/debian12-kube-v1.31.0 │ Kubernetes 1.31.0 on Debian 12 │ Debian │             │ True      │ 3500 │ available │ cloud-init   │            │      │
└──────────────────────────────┴────────────────────────────────┴────────┴─────────────┴───────────┴──────┴───────────┴──────────────┴────────────┴──────┘
Traceback (most recent call last):
  File "/home/user/.local/bin/linode", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/user/.local/share/pipx/venvs/linode-cli/lib/python3.13/site-packages/linodecli/__init__.py", line 234, in main
    cli.handle_command(parsed.command, parsed.action, args)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/linode-cli/lib/python3.13/site-packages/linodecli/cli.py", line 149, in handle_command
    operation.process_response_json(result, self.output_handler)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/linode-cli/lib/python3.13/site-packages/linodecli/baked/operation.py", line 543, in process_response_json
    handler.print_response(self.response_model, json)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/linode-cli/lib/python3.13/site-packages/linodecli/output/output_handler.py", line 163, in print_response
    self._scope_data_to_subtable(data, table_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/linode-cli/lib/python3.13/site-packages/linodecli/output/output_handler.py", line 209, in _scope_data_to_subtable
    raise IndexError(f"Segment {seg} missing from input data")
IndexError: Segment regions missing from input data


### Expected Behavior

Show the table, not the table + error.

### Actual Behavior

linodecli/output/output_handler.py
Method _scope_data_to_subtable, receives the variable table as "regions".
It gives that error because it can't split that value using ".".

### Steps to Reproduce

Just run the command.
I found this while looking for linode/debian12-kube-v1.31.0, but the same problem happens with other images.
This error appears in both tabular and text output. JSON is fine.

**Comment by yec-akamai** [comment]
Hi @leonardobdes, thank you for reporting this issue!

We've fixed it on the backend. Please use the latest CLI and spec version. Feel free to reopen this issue if you have further questions!
