### ISSUE TITLE
stackscript list generates AttributeError: 'MappedObject' object has no attribute 'example'

### ISSUE THREAD

**Issue by rmcintosh** [linode/linode-cli#8]
```
Traceback (most recent call last):
  File "/usr/local/bin/linode-cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/linodecli/cli.py", line 85, in main
    getattr(obj, cmd)(args, client, unparsed=unparsed)
  File "/usr/local/lib/python3.6/site-packages/linodecli/resources/stackscript.py", line 37, in list
    stackscripts = client.linode.get_stackscripts(mine_only=True)
  File "/usr/local/lib/python3.6/site-packages/linode/linode_client.py", line 44, in get_stackscripts
    return self.client._get_and_filter(StackScript, *filters)
  File "/usr/local/lib/python3.6/site-packages/linode/linode_client.py", line 495, in _get_and_filter
    return self._get_objects(obj_type.api_list(), obj_type, filters=parsed_filters)
  File "/usr/local/lib/python3.6/site-packages/linode/linode_client.py", line 410, in _get_objects
    page_url=formatted_endpoint[1:], cls=cls)
  File "/usr/local/lib/python3.6/site-packages/linode/mappings.py", line 34, in make_paginated_list
    l = make_list(json[key], client, parent_id=parent_id, cls=cls)
  File "/usr/local/lib/python3.6/site-packages/linode/mappings.py", line 28, in make_list
    o._populate(obj)
  File "/usr/local/lib/python3.6/site-packages/linode/objects/linode/stackscript.py", line 59, in _populate
    mapped_udfs.append(UserDefinedField(udf.name, udf.label, udf.example, t, \
AttributeError: 'MappedObject' object has no attribute 'example'
```

**Comment by rmcintosh** [comment]
... I'm dumb, this belongs in ```python-linode-api``` -> https://github.com/linode/python-linode-api/issues/33
